import { StyleSheet } from 'react-native-unistyles';
import { hs, vs } from '@/theme/metrics';

export const styles = StyleSheet.create((theme) => ({
  wrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  container: {
    position: 'relative',
    alignSelf: 'center',
    width: 'auto',
    minWidth: hs(264),
    maxWidth: hs(320),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    borderRadius: theme.metrics.borderRadius.full,
    borderWidth: 1,
    borderColor: theme.colors.border.subtle,
    backgroundColor:
      theme.colors.mode === 'dark' ? 'rgba(13, 23, 42, 0.76)' : 'rgba(255, 255, 255, 0.92)',
    paddingHorizontal: hs(4),
    paddingVertical: vs(4),
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: theme.colors.shadow.elevationMedium,
  },
  activeIndicator: {
    position: 'absolute',
    top: vs(4),
    bottom: vs(4),
    left: 0,
    borderRadius: theme.metrics.borderRadius.full,
    backgroundColor: theme.colors.background.app,
    borderWidth: 1,
    borderColor: theme.colors.border.subtle,
    shadowColor: theme.colors.shadow.color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: theme.colors.shadow.elevationSmall,
  },
  tab: {
    flex: 1,
    zIndex: 1,
    minHeight: vs(56),
    justifyContent: 'center',
  },
  tabInner: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.metrics.spacingV.p4,
    minWidth: hs(84),
    paddingHorizontal: theme.metrics.spacing.p12,
    paddingVertical: theme.metrics.spacingV.p8,
  },
  tabLabel: {
    fontSize: theme.fonts.size.xxs,
    fontFamily: theme.fonts.medium,
    fontWeight: '600',
    includeFontPadding: false,
    textAlign: 'center',
  },
}));
